services:
  - type: web
    name: rasant-api             # (ou o nome do seu serviço no Render)
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
